### PR TITLE
Make compatible with puppetserver 5.1

### PR DESCRIPTION
**Pull request by skrussell**
After upgrading my servers to be running puppetserver 5.1 last night, each puppet-agent run (that utilised this great IP type module) was failing with:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Syntax error at ']' at /etc/puppetlabs/code/environments/develop/modules/ip/types/address.pp:4:1`

Turns out the dangling commas in all of your Pattern/Variant declarations were causing it; removing them all fixed everything. Seems something in puppetserver 5.1 has been tightened-up to cause this.

### CODE REVIEW

**Comment by bodgit** [comment]
This also breaks with puppet-agent 5.2.0, same problem.

**Comment by carazzim0** [comment]
If the `,` gets removed at the end in the next-to-last line in every multiline file it works again.

**Comment by bodgit** [comment]
I think this behaviour was considered a regression and fixed in Puppet 5.3.1. Presumably it's made it into a comparable server release too. See https://tickets.puppetlabs.com/browse/PUP-7952.

**Comment by Phil-Friderici** [comment]
I have successfully @skrussell's patch on:
- Puppet 4.10.9 (Ruby 2.1.9)
- Puppet 5.0.1 (Ruby 2.4.1)
- Puppet 5.1.0 (Ruby 2.4.1)
- Puppet 5.2.0 (Ruby 2.4.1)
- Puppet 5.3.3 (Ruby 2.4.1)

If this could get merged we wouldn't need to exclude Puppet 5.2 support for our modules :)

**Comment by Phil-Friderici** [comment]
THX!

**Pull request merged**
