### PR TITLE
Patch to allow /0 mask

### PR DESCRIPTION
**Pull request by freddebacker**
Allow 0.0.0.0/0 and ::0/0 as valid.

(Example usecase: manage an ACLs or a route for everywhere...)

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thank you @freddebacker!! Could you please add these entries to the spec tests and to the README under the examples for https://github.com/thrnio/puppet-ip#ipaddressv4 and https://github.com/thrnio/puppet-ip#ipaddressv6

**Comment by freddebacker** [comment]
I've added the examples to the README (and fixed a bug in it.)
I also fixed the regexes in more places that I initially forgot.

Where do I find the spec tests?

**Comment by thrnio** [comment]
@freddebacker It looks like the spec tests never got pulled in here, so I think just updating the README is probably fine for now. What do you think @ghoneycutt?

**Comment by ghoneycutt** [comment]
This module is no longer maintained. Its functionality has been incorporated in https://github.com/puppetlabs/puppetlabs-stdlib as of version 4.25.0. If this is still an issue, please target that code base.

**Pull request closed without merging**
